name: final5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  accordion: ^2.6.0
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  ticket_widget: ^1.0.2
  transparent_image: ^2.0.1
  flutter_tts: ^3.8.3
  url_launcher: ^6.1.6
  gif: ^2.3.0
  # flutter_gif: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
      - assets/images/intropage.jpeg
      - assets/images/intropage2.jpeg
      - assets/images/intopage3.jpeg
      - assets/images/intropage4.jpeg
      - assets/images/p1.jpeg
      - assets/images/p2.jpeg
      - assets/images/p3.jpeg
      - assets/images/p4.jpeg
      - assets/images/p5.jpeg
      - assets/images/p6.jpeg
      - assets/images/m1.png
      - assets/images/m2.png
      - assets/images/m3.png
      - assets/images/m4.png
      - assets/images/m5.png
      - assets/images/intro1.jpeg
      - assets/images/contactImage.png
      - assets/images/bar_code.jpg
      - assets/images/bg-dark.png
      - assets/images/bg-light.png
      - assets/images/card_bg.png
      - assets/images/mastercard.png
      - assets/images/chat (1).png
      - assets/images/character2.jpeg
      - assets/images/character1.jpeg
      - assets/images/characteree2.jpg
      - assets/images/characteree1.jpg
      - assets/images/file1.png
      - assets/images/file2.png
      - assets/images/file3.png
      - assets/images/file4.png
      - assets/images/file5.png
      - assets/images/file6.png
      - assets/images/file7.png
      - assets/images/file8.png
      - assets/images/file9.png
      - assets/images/file10.png
      - assets/images/file11.png
      - assets/images/file12.png
      - assets/images/file13.png
      - assets/images/file14.png
      - assets/images/file15.png
      - assets/images/file16.png
      - assets/images/file17.png
      - assets/images/file18.png
      - assets/images/file19.png
      - assets/images/file20.png
      - assets/images/file21.png
      - assets/images/file22.png
      - assets/images/file23.png
      - assets/images/file24.png
      - assets/images/file25.png
      - assets/images/file26.png
      - assets/images/file27.png
      - assets/images/file28.png
      - assets/images/animation.gif
      - assets/images/animation_used.gif

